name: Testar e Integrar com a Main

on:
  push:
    branches:
      - 'dev'

jobs:
  test:
    name: Compilar e Testar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compilar o projeto (Build)
        run: cargo build --verbose

      - name: Rodar os testes
        run: cargo test --verbose

  merge-to-main:
    name: Fazer Merge para a Main
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout do código com histórico completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fazer merge e push para a main
        run: |
          set -eux # Para o script se houver erro e mostra os comandos executados.

          # Configura o Git com um usuário para o commit de merge.
          git config --global user.name 'alovictor'
          git config --global user.email 'victor.neves@tutanota.com'

          # Muda para a branch de destino.
          git checkout main

          # Garante que a branch main local está atualizada com a remota.
          git pull origin main

          # Faz o merge da branch que disparou o workflow.
          # A variável ${GITEA_REF} contém a referência completa (ex: refs/heads/dev).
          git merge ${{ gitea.ref }} --no-ff -m "Merge automático da branch '${{ gitea.ref }}' via Gitea Actions"

          # Envia as alterações para o repositório remoto.
          # O GITEA_TOKEN é fornecido automaticamente pelo runner e tem permissão para o push.
          git push origin main