name: Testar e Integrar com a Main

on:
  push:
    branches:
      - "dev"

jobs:
  test:
    name: Compilar e Testar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar ambiente Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Compilar o projeto (Build)
        run: cargo build --verbose

      - name: Rodar os testes
        run: cargo test --verbose
